name: deploy
on:
  workflow_dispatch:  # 改为手动触发，防止崩溃

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Spring Boot App
        run: ./gradlew build -x test

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "app/build/libs/*.jar"
          target: "/home/ec2-user/build/libs/"

      - name: Restart Service on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
<<<<<<< HEAD
            echo "Restarting Spring Boot service..."
            sudo systemctl restart chatapp
=======
            if [ ! -d "chat-app-server" ]; then
              git clone https://github.com/yanshuyu280042/chat-app-server.git
            fi
            cd chat-app-server
            git pull origin main
            ./gradlew clean build -x test
>>>>>>> 876e016 (Final deploy: fix upload target path to match service)

