name: Run Spring Boot Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test --tests "com.example.demo.AuthControllerTest"

      - name: Archive test reports (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/test-results/test

